///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MBA_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MBA_TestingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("53e9ae04-53f5-4be7-8e14-0d53648e3be7")]
    public partial class MBA_TestingRepository : RepoGenBaseFolder
    {
        static MBA_TestingRepository instance = new MBA_TestingRepository();
        MBA_TestingRepositoryFolders.ChromeBrowserAppFolder _chromebrowser;
        MBA_TestingRepositoryFolders.MBA_WebAppFolder _mba_web;
        MBA_TestingRepositoryFolders.AJOA_PageAppFolder _ajoa_page;

        /// <summary>
        /// Gets the singleton class instance representing the MBA_TestingRepository element repository.
        /// </summary>
        [RepositoryFolder("53e9ae04-53f5-4be7-8e14-0d53648e3be7")]
        public static MBA_TestingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MBA_TestingRepository() 
            : base("MBA_TestingRepository", "/", null, 0, false, "53e9ae04-53f5-4be7-8e14-0d53648e3be7", ".\\RepositoryImages\\MBA_TestingRepository53e9ae04.rximgres")
        {
            _chromebrowser = new MBA_TestingRepositoryFolders.ChromeBrowserAppFolder(this);
            _mba_web = new MBA_TestingRepositoryFolders.MBA_WebAppFolder(this);
            _ajoa_page = new MBA_TestingRepositoryFolders.AJOA_PageAppFolder(this);
        }

#region Variables

        string _parentMenu = "\"\"";

        /// <summary>
        /// Gets or sets the value of variable parentMenu.
        /// </summary>
        [TestVariable("602870d4-cc95-43b7-9320-30bb1028f22d")]
        public string parentMenu
        {
            get { return _parentMenu; }
            set { _parentMenu = value; }
        }

        string _parentname = "";

        /// <summary>
        /// Gets or sets the value of variable parentname.
        /// </summary>
        [TestVariable("41c02034-e087-42e3-af49-3ed289383d6f")]
        public string parentname
        {
            get { return _parentname; }
            set { _parentname = value; }
        }

        string _parentList = "";

        /// <summary>
        /// Gets or sets the value of variable parentList.
        /// </summary>
        [TestVariable("f72578b9-35be-4161-acce-56d541e0c12c")]
        public string parentList
        {
            get { return _parentList; }
            set { _parentList = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("53e9ae04-53f5-4be7-8e14-0d53648e3be7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ChromeBrowser folder.
        /// </summary>
        [RepositoryFolder("0266cbe2-afed-4ffb-9df9-01b9feaa50e3")]
        public virtual MBA_TestingRepositoryFolders.ChromeBrowserAppFolder ChromeBrowser
        {
            get { return _chromebrowser; }
        }

        /// <summary>
        /// The MBA_Web folder.
        /// </summary>
        [RepositoryFolder("6e43a3f2-6ed4-45d3-8fa5-a9643fc2a4fa")]
        public virtual MBA_TestingRepositoryFolders.MBA_WebAppFolder MBA_Web
        {
            get { return _mba_web; }
        }

        /// <summary>
        /// The AJOA_Page folder.
        /// </summary>
        [RepositoryFolder("355531b7-a670-44f7-9e86-516d6632bdc3")]
        public virtual MBA_TestingRepositoryFolders.AJOA_PageAppFolder AJOA_Page
        {
            get { return _ajoa_page; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MBA_TestingRepositoryFolders
    {
        /// <summary>
        /// The ChromeBrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("0266cbe2-afed-4ffb-9df9-01b9feaa50e3")]
        public partial class ChromeBrowserAppFolder : RepoGenBaseFolder
        {
            MBA_TestingRepositoryFolders.ExternalProtocolRequestFolder _externalprotocolrequest;
            RepoItemInfo _addressandsearchbarInfo;
            RepoItemInfo _backbuttonInfo;
            RepoItemInfo _refreshbuttonInfo;
            RepoItemInfo _closetabbuttonInfo;
            RepoItemInfo _closebrowserbuttonInfo;
            RepoItemInfo _chrometabloadingspinnerInfo;

            /// <summary>
            /// Creates a new ChromeBrowser  folder.
            /// </summary>
            public ChromeBrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ChromeBrowser", "/form[@title~'Google\\ Chrome$']", parentFolder, 1000, null, true, "0266cbe2-afed-4ffb-9df9-01b9feaa50e3", "")
            {
                _externalprotocolrequest = new MBA_TestingRepositoryFolders.ExternalProtocolRequestFolder(this);
                _addressandsearchbarInfo = new RepoItemInfo(this, "AddressAndSearchBar", ".//container[@accessiblename='Google Chrome']//container[@accessiblerole='Client']//text[@accessiblename='Address and search bar']", "", 5000, null, "aa48dbda-c89e-4952-874a-8a14dd33ba32");
                _backbuttonInfo = new RepoItemInfo(this, "BackButton", ".//container[@accessiblename='Google Chrome']//button[@accessiblename='Back']", "", 1000, null, "1cf07b3c-38fa-4c01-a67d-345fe00d7a05");
                _refreshbuttonInfo = new RepoItemInfo(this, "RefreshButton", ".//container[@accessiblename='Google Chrome']//button[@accessiblename='Reload']", "", 1000, null, "c627397b-68cd-448d-8a2c-e1ad914ab5b9");
                _closetabbuttonInfo = new RepoItemInfo(this, "CloseTabButton", ".//container[@accessiblename='Google Chrome']//tabpage[@accessiblename>'MedicalDirector Helix']/button[@accessiblename='Close']", "", 1000, null, "d5ec3542-90a4-4a2f-8869-4921f8b05fed");
                _closebrowserbuttonInfo = new RepoItemInfo(this, "CloseBrowserButton", ".//titlebar/button[@accessiblename='Close']", "", 1000, null, "99f8cc77-8ee2-4636-a5ec-1e4a5a0f3e31");
                _chrometabloadingspinnerInfo = new RepoItemInfo(this, "ChromeTabLoadingSpinner", ".//container[@accessiblename='Google Chrome']//tabpage/container[@accessiblerole='Client']", "", 30000, null, "f741d817-e095-4848-adfa-1815b1fa56d1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0266cbe2-afed-4ffb-9df9-01b9feaa50e3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0266cbe2-afed-4ffb-9df9-01b9feaa50e3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item.
            /// </summary>
            [RepositoryItem("aa48dbda-c89e-4952-874a-8a14dd33ba32")]
            public virtual Ranorex.Text AddressAndSearchBar
            {
                get
                {
                    return _addressandsearchbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item info.
            /// </summary>
            [RepositoryItemInfo("aa48dbda-c89e-4952-874a-8a14dd33ba32")]
            public virtual RepoItemInfo AddressAndSearchBarInfo
            {
                get
                {
                    return _addressandsearchbarInfo;
                }
            }

            /// <summary>
            /// The BackButton item.
            /// </summary>
            [RepositoryItem("1cf07b3c-38fa-4c01-a67d-345fe00d7a05")]
            public virtual Ranorex.Button BackButton
            {
                get
                {
                    return _backbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BackButton item info.
            /// </summary>
            [RepositoryItemInfo("1cf07b3c-38fa-4c01-a67d-345fe00d7a05")]
            public virtual RepoItemInfo BackButtonInfo
            {
                get
                {
                    return _backbuttonInfo;
                }
            }

            /// <summary>
            /// The RefreshButton item.
            /// </summary>
            [RepositoryItem("c627397b-68cd-448d-8a2c-e1ad914ab5b9")]
            public virtual Ranorex.Button RefreshButton
            {
                get
                {
                    return _refreshbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RefreshButton item info.
            /// </summary>
            [RepositoryItemInfo("c627397b-68cd-448d-8a2c-e1ad914ab5b9")]
            public virtual RepoItemInfo RefreshButtonInfo
            {
                get
                {
                    return _refreshbuttonInfo;
                }
            }

            /// <summary>
            /// The CloseTabButton item.
            /// </summary>
            [RepositoryItem("d5ec3542-90a4-4a2f-8869-4921f8b05fed")]
            public virtual Ranorex.Button CloseTabButton
            {
                get
                {
                    return _closetabbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseTabButton item info.
            /// </summary>
            [RepositoryItemInfo("d5ec3542-90a4-4a2f-8869-4921f8b05fed")]
            public virtual RepoItemInfo CloseTabButtonInfo
            {
                get
                {
                    return _closetabbuttonInfo;
                }
            }

            /// <summary>
            /// The CloseBrowserButton item.
            /// </summary>
            [RepositoryItem("99f8cc77-8ee2-4636-a5ec-1e4a5a0f3e31")]
            public virtual Ranorex.Button CloseBrowserButton
            {
                get
                {
                    return _closebrowserbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseBrowserButton item info.
            /// </summary>
            [RepositoryItemInfo("99f8cc77-8ee2-4636-a5ec-1e4a5a0f3e31")]
            public virtual RepoItemInfo CloseBrowserButtonInfo
            {
                get
                {
                    return _closebrowserbuttonInfo;
                }
            }

            /// <summary>
            /// The ChromeTabLoadingSpinner item.
            /// </summary>
            [RepositoryItem("f741d817-e095-4848-adfa-1815b1fa56d1")]
            public virtual Ranorex.Container ChromeTabLoadingSpinner
            {
                get
                {
                    return _chrometabloadingspinnerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ChromeTabLoadingSpinner item info.
            /// </summary>
            [RepositoryItemInfo("f741d817-e095-4848-adfa-1815b1fa56d1")]
            public virtual RepoItemInfo ChromeTabLoadingSpinnerInfo
            {
                get
                {
                    return _chrometabloadingspinnerInfo;
                }
            }

            /// <summary>
            /// The ExternalProtocolRequest folder.
            /// </summary>
            [RepositoryFolder("5146fb27-6f49-46f3-a962-3f388501caa6")]
            public virtual MBA_TestingRepositoryFolders.ExternalProtocolRequestFolder ExternalProtocolRequest
            {
                get { return _externalprotocolrequest; }
            }
        }

        /// <summary>
        /// The ExternalProtocolRequestFolder folder.
        /// </summary>
        [RepositoryFolder("5146fb27-6f49-46f3-a962-3f388501caa6")]
        public partial class ExternalProtocolRequestFolder : RepoGenBaseFolder
        {
            RepoItemInfo _launchapplicationbuttonInfo;
            RepoItemInfo _donothingbuttonInfo;
            RepoItemInfo _rememberchoicecheckboxInfo;

            /// <summary>
            /// Creates a new ExternalProtocolRequest  folder.
            /// </summary>
            public ExternalProtocolRequestFolder(RepoGenBaseFolder parentFolder) :
                    base("ExternalProtocolRequest", "form[@accessiblename='External Protocol Request']", parentFolder, 30000, null, false, "5146fb27-6f49-46f3-a962-3f388501caa6", "")
            {
                _launchapplicationbuttonInfo = new RepoItemInfo(this, "LaunchApplicationButton", ".//button[@accessiblename='Launch Application']", "", 30000, null, "2f9e5e8f-edbc-4f5d-a2da-f5d476cb0568");
                _donothingbuttonInfo = new RepoItemInfo(this, "DoNothingButton", ".//button[@accessiblename='Do Nothing']", "", 30000, null, "a662854f-1ef6-4923-80f3-5d2ec9b79b1a");
                _rememberchoicecheckboxInfo = new RepoItemInfo(this, "RememberChoiceCheckbox", ".//checkbox[@accessiblename~'Remember my choice for all links of this type']", "", 30000, null, "0f7d8795-909a-417b-b0c9-d7f0c9f2d7d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5146fb27-6f49-46f3-a962-3f388501caa6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5146fb27-6f49-46f3-a962-3f388501caa6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LaunchApplicationButton item.
            /// </summary>
            [RepositoryItem("2f9e5e8f-edbc-4f5d-a2da-f5d476cb0568")]
            public virtual Ranorex.Button LaunchApplicationButton
            {
                get
                {
                    return _launchapplicationbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LaunchApplicationButton item info.
            /// </summary>
            [RepositoryItemInfo("2f9e5e8f-edbc-4f5d-a2da-f5d476cb0568")]
            public virtual RepoItemInfo LaunchApplicationButtonInfo
            {
                get
                {
                    return _launchapplicationbuttonInfo;
                }
            }

            /// <summary>
            /// The DoNothingButton item.
            /// </summary>
            [RepositoryItem("a662854f-1ef6-4923-80f3-5d2ec9b79b1a")]
            public virtual Ranorex.Button DoNothingButton
            {
                get
                {
                    return _donothingbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DoNothingButton item info.
            /// </summary>
            [RepositoryItemInfo("a662854f-1ef6-4923-80f3-5d2ec9b79b1a")]
            public virtual RepoItemInfo DoNothingButtonInfo
            {
                get
                {
                    return _donothingbuttonInfo;
                }
            }

            /// <summary>
            /// The RememberChoiceCheckbox item.
            /// </summary>
            [RepositoryItem("0f7d8795-909a-417b-b0c9-d7f0c9f2d7d6")]
            public virtual Ranorex.CheckBox RememberChoiceCheckbox
            {
                get
                {
                    return _rememberchoicecheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The RememberChoiceCheckbox item info.
            /// </summary>
            [RepositoryItemInfo("0f7d8795-909a-417b-b0c9-d7f0c9f2d7d6")]
            public virtual RepoItemInfo RememberChoiceCheckboxInfo
            {
                get
                {
                    return _rememberchoicecheckboxInfo;
                }
            }
        }

        /// <summary>
        /// The MBA_WebAppFolder folder.
        /// </summary>
        [RepositoryFolder("6e43a3f2-6ed4-45d3-8fa5-a9643fc2a4fa")]
        public partial class MBA_WebAppFolder : RepoGenBaseFolder
        {
            MBA_TestingRepositoryFolders.CatalogFolder _catalog;
            MBA_TestingRepositoryFolders.LoginFormFolder _loginform;
            MBA_TestingRepositoryFolders.AddNewProductFolder _addnewproduct;
            MBA_TestingRepositoryFolders.HomePageFolder _homepage;

            /// <summary>
            /// Creates a new MBA_Web  folder.
            /// </summary>
            public MBA_WebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MBA_Web", "/dom[@domain='ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "6e43a3f2-6ed4-45d3-8fa5-a9643fc2a4fa", "")
            {
                _catalog = new MBA_TestingRepositoryFolders.CatalogFolder(this);
                _loginform = new MBA_TestingRepositoryFolders.LoginFormFolder(this);
                _addnewproduct = new MBA_TestingRepositoryFolders.AddNewProductFolder(this);
                _homepage = new MBA_TestingRepositoryFolders.HomePageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6e43a3f2-6ed4-45d3-8fa5-a9643fc2a4fa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6e43a3f2-6ed4-45d3-8fa5-a9643fc2a4fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Catalog folder.
            /// </summary>
            [RepositoryFolder("e7ae08a2-9c12-4918-8b35-e148eedf8dd5")]
            public virtual MBA_TestingRepositoryFolders.CatalogFolder Catalog
            {
                get { return _catalog; }
            }

            /// <summary>
            /// The LoginForm folder.
            /// </summary>
            [RepositoryFolder("396e6d83-9aa5-426f-87be-d7c7903a039b")]
            public virtual MBA_TestingRepositoryFolders.LoginFormFolder LoginForm
            {
                get { return _loginform; }
            }

            /// <summary>
            /// The AddNewProduct folder.
            /// </summary>
            [RepositoryFolder("a185a088-d972-4666-94e6-f5a95e996d02")]
            public virtual MBA_TestingRepositoryFolders.AddNewProductFolder AddNewProduct
            {
                get { return _addnewproduct; }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("bf7565d0-3668-4383-ad4c-657dfd2d93e8")]
            public virtual MBA_TestingRepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }
        }

        /// <summary>
        /// The CatalogFolder folder.
        /// </summary>
        [RepositoryFolder("e7ae08a2-9c12-4918-8b35-e148eedf8dd5")]
        public partial class CatalogFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menucatalogInfo;
            RepoItemInfo _menuproductInfo;
            RepoItemInfo _txtsearchnameInfo;
            RepoItemInfo _btnfilterInfo;
            RepoItemInfo _listnameproductInfo;
            RepoItemInfo _btnnextpageInfo;
            RepoItemInfo _checkcatalogopenInfo;
            RepoItemInfo _newprodInfo;

            /// <summary>
            /// Creates a new Catalog  folder.
            /// </summary>
            public CatalogFolder(RepoGenBaseFolder parentFolder) :
                    base("Catalog", "", parentFolder, 0, null, false, "e7ae08a2-9c12-4918-8b35-e148eedf8dd5", "")
            {
                _menucatalogInfo = new RepoItemInfo(this, "MenuCatalog", ".//a[@innertext=' Catalog']", ".//li[#'menu-catalog']/a[@innertext=' Catalog']", 30000, null, "d50e5908-4d54-4745-a25e-8b393851e3a4");
                _menuproductInfo = new RepoItemInfo(this, "MenuProduct", ".//li[#'menu-catalog']//a[@innertext='Products']", ".//li[#'menu-catalog']//a[@innertext='Products']", 30000, null, "94a0b189-ff13-4956-970b-f2b888d3a1d6");
                _txtsearchnameInfo = new RepoItemInfo(this, "TxtSearchName", ".//input[#'input-name']", ".//input[#'input-name']", 30000, null, "4f9599c5-663b-4a41-916c-d4bd5948651b");
                _btnfilterInfo = new RepoItemInfo(this, "btnFilter", ".//button[#'button-filter']", ".//button[#'button-filter']", 30000, null, "9d626c63-2a23-4bcf-9225-c3109c6c7cde");
                _listnameproductInfo = new RepoItemInfo(this, "ListNameProduct", ".//table[@class='table table-bordered table-hover']/tbody", ".//div[#'content']/div[2]/div/div[2]/div/div[2]", 30000, null, "e9e90864-21d7-49c6-b33e-0e6e13bdd092");
                _btnnextpageInfo = new RepoItemInfo(this, "btnNextPage", ".//div[#'content']//a[@class='next']", ".//div[#'content']//a[@innertext='>']", 30000, null, "22cad3fc-63be-4e4f-8362-fc390ffc3d97");
                _checkcatalogopenInfo = new RepoItemInfo(this, "CheckCatalogOpen", ".//ul[#'menu']//li[#'menu-catalog']//a[@aria-expanded='true']", "element", 30000, null, "5582b3bf-ea44-47ee-889e-a07b94c25ffb");
                _newprodInfo = new RepoItemInfo(this, "NewProd", ".//*[@id='form-product']/div/table/tbody/tr/td[@innertext<'Samsung Galaxy S10 5G 256GB (Majestic Black)']", "element", 30000, null, "50cb0287-f818-4a3b-8900-78d0587d8256");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7ae08a2-9c12-4918-8b35-e148eedf8dd5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuCatalog item.
            /// </summary>
            [RepositoryItem("d50e5908-4d54-4745-a25e-8b393851e3a4")]
            public virtual Ranorex.ATag MenuCatalog
            {
                get
                {
                    return _menucatalogInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MenuCatalog item info.
            /// </summary>
            [RepositoryItemInfo("d50e5908-4d54-4745-a25e-8b393851e3a4")]
            public virtual RepoItemInfo MenuCatalogInfo
            {
                get
                {
                    return _menucatalogInfo;
                }
            }

            /// <summary>
            /// The MenuProduct item.
            /// </summary>
            [RepositoryItem("94a0b189-ff13-4956-970b-f2b888d3a1d6")]
            public virtual Ranorex.ATag MenuProduct
            {
                get
                {
                    return _menuproductInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MenuProduct item info.
            /// </summary>
            [RepositoryItemInfo("94a0b189-ff13-4956-970b-f2b888d3a1d6")]
            public virtual RepoItemInfo MenuProductInfo
            {
                get
                {
                    return _menuproductInfo;
                }
            }

            /// <summary>
            /// The TxtSearchName item.
            /// </summary>
            [RepositoryItem("4f9599c5-663b-4a41-916c-d4bd5948651b")]
            public virtual Ranorex.InputTag TxtSearchName
            {
                get
                {
                    return _txtsearchnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtSearchName item info.
            /// </summary>
            [RepositoryItemInfo("4f9599c5-663b-4a41-916c-d4bd5948651b")]
            public virtual RepoItemInfo TxtSearchNameInfo
            {
                get
                {
                    return _txtsearchnameInfo;
                }
            }

            /// <summary>
            /// The btnFilter item.
            /// </summary>
            [RepositoryItem("9d626c63-2a23-4bcf-9225-c3109c6c7cde")]
            public virtual Ranorex.Button btnFilter
            {
                get
                {
                    return _btnfilterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnFilter item info.
            /// </summary>
            [RepositoryItemInfo("9d626c63-2a23-4bcf-9225-c3109c6c7cde")]
            public virtual RepoItemInfo btnFilterInfo
            {
                get
                {
                    return _btnfilterInfo;
                }
            }

            /// <summary>
            /// The ListNameProduct item.
            /// </summary>
            [RepositoryItem("e9e90864-21d7-49c6-b33e-0e6e13bdd092")]
            public virtual Ranorex.TBodyTag ListNameProduct
            {
                get
                {
                    return _listnameproductInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The ListNameProduct item info.
            /// </summary>
            [RepositoryItemInfo("e9e90864-21d7-49c6-b33e-0e6e13bdd092")]
            public virtual RepoItemInfo ListNameProductInfo
            {
                get
                {
                    return _listnameproductInfo;
                }
            }

            /// <summary>
            /// The btnNextPage item.
            /// </summary>
            [RepositoryItem("22cad3fc-63be-4e4f-8362-fc390ffc3d97")]
            public virtual Ranorex.ATag btnNextPage
            {
                get
                {
                    return _btnnextpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnNextPage item info.
            /// </summary>
            [RepositoryItemInfo("22cad3fc-63be-4e4f-8362-fc390ffc3d97")]
            public virtual RepoItemInfo btnNextPageInfo
            {
                get
                {
                    return _btnnextpageInfo;
                }
            }

            /// <summary>
            /// The CheckCatalogOpen item.
            /// </summary>
            [RepositoryItem("5582b3bf-ea44-47ee-889e-a07b94c25ffb")]
            public virtual Ranorex.ATag CheckCatalogOpen
            {
                get
                {
                    return _checkcatalogopenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CheckCatalogOpen item info.
            /// </summary>
            [RepositoryItemInfo("5582b3bf-ea44-47ee-889e-a07b94c25ffb")]
            public virtual RepoItemInfo CheckCatalogOpenInfo
            {
                get
                {
                    return _checkcatalogopenInfo;
                }
            }

            /// <summary>
            /// The NewProd item.
            /// </summary>
            [RepositoryItem("50cb0287-f818-4a3b-8900-78d0587d8256")]
            public virtual Ranorex.TdTag NewProd
            {
                get
                {
                    return _newprodInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The NewProd item info.
            /// </summary>
            [RepositoryItemInfo("50cb0287-f818-4a3b-8900-78d0587d8256")]
            public virtual RepoItemInfo NewProdInfo
            {
                get
                {
                    return _newprodInfo;
                }
            }
        }

        /// <summary>
        /// The LoginFormFolder folder.
        /// </summary>
        [RepositoryFolder("396e6d83-9aa5-426f-87be-d7c7903a039b")]
        public partial class LoginFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new LoginForm  folder.
            /// </summary>
            public LoginFormFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginForm", "", parentFolder, 0, null, false, "396e6d83-9aa5-426f-87be-d7c7903a039b", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "txtUserName", ".//input[#'input-username']", ".//input[#'input-username']", 30000, null, "796f953a-9664-4a68-9041-846acd87b883");
                _txtpasswordInfo = new RepoItemInfo(this, "txtPassWord", ".//input[#'input-password']", ".//input[#'input-password']", 30000, null, "62b730b2-b2bc-492b-b7b7-f70c5595b3c7");
                _btnloginInfo = new RepoItemInfo(this, "btnLogin", ".//form[@action='https://ptn-test1.oc.mbasrv.com/sbe/index.php?route=common/login']//button[@innertext=' Login']", ".//div[#'content']//button[@innertext=' Login']", 30000, null, "7f593a36-0e2a-406a-9dfe-f56ff5c6cdfc");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("396e6d83-9aa5-426f-87be-d7c7903a039b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtUserName item.
            /// </summary>
            [RepositoryItem("796f953a-9664-4a68-9041-846acd87b883")]
            public virtual Ranorex.InputTag txtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtUserName item info.
            /// </summary>
            [RepositoryItemInfo("796f953a-9664-4a68-9041-846acd87b883")]
            public virtual RepoItemInfo txtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The txtPassWord item.
            /// </summary>
            [RepositoryItem("62b730b2-b2bc-492b-b7b7-f70c5595b3c7")]
            public virtual Ranorex.InputTag txtPassWord
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPassWord item info.
            /// </summary>
            [RepositoryItemInfo("62b730b2-b2bc-492b-b7b7-f70c5595b3c7")]
            public virtual RepoItemInfo txtPassWordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The btnLogin item.
            /// </summary>
            [RepositoryItem("7f593a36-0e2a-406a-9dfe-f56ff5c6cdfc")]
            public virtual Ranorex.Button btnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLogin item info.
            /// </summary>
            [RepositoryItemInfo("7f593a36-0e2a-406a-9dfe-f56ff5c6cdfc")]
            public virtual RepoItemInfo btnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The AddNewProductFolder folder.
        /// </summary>
        [RepositoryFolder("a185a088-d972-4666-94e6-f5a95e996d02")]
        public partial class AddNewProductFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaddproductInfo;
            RepoItemInfo _menuitemdataInfo;
            RepoItemInfo _menuitemlinkInfo;
            RepoItemInfo _menuitemimageInfo;
            RepoItemInfo _txtprodnameInfo;
            RepoItemInfo _txtmetatagtitleInfo;
            RepoItemInfo _txtmodelInfo;
            RepoItemInfo _checkboxajoaInfo;
            RepoItemInfo _btnimageInfo;
            RepoItemInfo _btneditimageInfo;
            RepoItemInfo _imagefolderInfo;
            RepoItemInfo _txtdateavailableInfo;
            RepoItemInfo _txtenddateInfo;
            RepoItemInfo _enddateInfo;
            RepoItemInfo _btnsaveInfo;
            RepoItemInfo _menucheckboxInfo;
            RepoItemInfo _txtpriceInfo;

            /// <summary>
            /// Creates a new AddNewProduct  folder.
            /// </summary>
            public AddNewProductFolder(RepoGenBaseFolder parentFolder) :
                    base("AddNewProduct", "", parentFolder, 0, null, false, "a185a088-d972-4666-94e6-f5a95e996d02", "")
            {
                _btnaddproductInfo = new RepoItemInfo(this, "btnAddProduct", ".//div[#'content']//a[@data-original-title='Add New']", ".//div[#'content']//a[@title='']", 30000, null, "eb29577a-d763-46f0-b2e2-57d52661dfdd");
                _menuitemdataInfo = new RepoItemInfo(this, "MenuItemData", ".//form[#'form-product']//a[@innertext='Data']", ".//form[#'form-product']//a[@innertext='Data']", 30000, null, "9751bce3-783b-449f-863a-052649d51f71");
                _menuitemlinkInfo = new RepoItemInfo(this, "MenuItemLink", ".//form[#'form-product']//a[@innertext='Links']", ".//form[#'form-product']//a[@innertext='Links']", 30000, null, "56584f50-672c-4871-9fd6-6de7ce53df87");
                _menuitemimageInfo = new RepoItemInfo(this, "MenuItemImage", ".//form[#'form-product']//a[@innertext='Image']", ".//form[#'form-product']//a[@innertext='Image']", 30000, null, "c534f3e8-ec0d-46c8-a2c6-2c602c153371");
                _txtprodnameInfo = new RepoItemInfo(this, "txtProdName", ".//div[#'tab-general']//input[@name='product_description[1][name]']", ".//div[#'tab-general']//input[@name='product_description[1][name]']", 30000, null, "f3331ba9-7219-4b94-8bfc-6c789f1991c6");
                _txtmetatagtitleInfo = new RepoItemInfo(this, "txtMetatagtitle", ".//div[#'tab-general']//input[@name='product_description[1][meta_title]']", "", 30000, null, "3f720bf1-22be-4f42-8722-06ecd934e143");
                _txtmodelInfo = new RepoItemInfo(this, "txtModel", ".//input[#'input-model']", ".//input[#'input-model']", 30000, null, "0167ac50-cdbd-4e40-a8ae-284190ece8a8");
                _checkboxajoaInfo = new RepoItemInfo(this, "CheckBoxAJOA", ".//div[#'tab-links']//input[@value='1']", ".//div[#'tab-links']/div[4]/div/div/div[3]/label[@innertext>'']", 30000, null, "183206ea-b5ed-4809-b3d2-f40e43d8183a");
                _btnimageInfo = new RepoItemInfo(this, "btnImage", ".//a[#'thumb-image']", ".//a[#'thumb-image']", 30000, null, "2880720d-213b-4ee8-8fd2-b72d05237533");
                _btneditimageInfo = new RepoItemInfo(this, "btnEditImage", ".//button[#'button-image']", ".//button[#'button-image']/i", 30000, null, "596bc8be-0bef-4597-abec-a25e6efea4fb");
                _imagefolderInfo = new RepoItemInfo(this, "ImageFolder", ".//div[#'filemanager']//i", ".//div[#'filemanager']/div/div[2]/div[2]/div[1]/div/a[@href>'https://ptn-test1.oc.mbas']/i", 30000, null, "21706f63-8ee2-4f6e-a14d-20e44c9cb734");
                _txtdateavailableInfo = new RepoItemInfo(this, "txtDateAvailable", ".//input[#'input-date-available']", ".//input[#'input-date-available']", 30000, null, "9a1de261-fd81-4a25-9294-74110587558f");
                _txtenddateInfo = new RepoItemInfo(this, "txtEndDate", ".//input[#'input-end-date-available']", ".//input[#'input-end-date-available']", 30000, null, "63d4a7d4-5b29-45c2-82dc-5acc6a7464d3");
                _enddateInfo = new RepoItemInfo(this, "EndDate", ".//input[#'input-end-date-available']", ".//input[#'input-end-date-available']", 30000, null, "e6eaec65-3ed8-4627-a7c6-709e7bf8c4d6");
                _btnsaveInfo = new RepoItemInfo(this, "btnSave", ".//div[#'content']//button[@data-original-title='Save']", ".//div[#'content']//button[@title='']", 30000, null, "3b596eec-9f9e-4e4b-8675-80d11414cf2c");
                _menucheckboxInfo = new RepoItemInfo(this, "MenuCheckbox", ".//div[#'tab-links']/div[4]//div[@class='well well-sm']", ".//div[#'tab-links']/div[4]/div/div", 30000, null, "f22c1afc-be1e-4bdd-8287-2ffae478de51");
                _txtpriceInfo = new RepoItemInfo(this, "txtPrice", ".//input[#'input-price']", ".//input[#'input-price']", 30000, null, "f262e6e4-5078-46cd-9560-f43c76c2cce8");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a185a088-d972-4666-94e6-f5a95e996d02")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAddProduct item.
            /// </summary>
            [RepositoryItem("eb29577a-d763-46f0-b2e2-57d52661dfdd")]
            public virtual Ranorex.ATag btnAddProduct
            {
                get
                {
                    return _btnaddproductInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnAddProduct item info.
            /// </summary>
            [RepositoryItemInfo("eb29577a-d763-46f0-b2e2-57d52661dfdd")]
            public virtual RepoItemInfo btnAddProductInfo
            {
                get
                {
                    return _btnaddproductInfo;
                }
            }

            /// <summary>
            /// The MenuItemData item.
            /// </summary>
            [RepositoryItem("9751bce3-783b-449f-863a-052649d51f71")]
            public virtual Ranorex.ATag MenuItemData
            {
                get
                {
                    return _menuitemdataInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MenuItemData item info.
            /// </summary>
            [RepositoryItemInfo("9751bce3-783b-449f-863a-052649d51f71")]
            public virtual RepoItemInfo MenuItemDataInfo
            {
                get
                {
                    return _menuitemdataInfo;
                }
            }

            /// <summary>
            /// The MenuItemLink item.
            /// </summary>
            [RepositoryItem("56584f50-672c-4871-9fd6-6de7ce53df87")]
            public virtual Ranorex.ATag MenuItemLink
            {
                get
                {
                    return _menuitemlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MenuItemLink item info.
            /// </summary>
            [RepositoryItemInfo("56584f50-672c-4871-9fd6-6de7ce53df87")]
            public virtual RepoItemInfo MenuItemLinkInfo
            {
                get
                {
                    return _menuitemlinkInfo;
                }
            }

            /// <summary>
            /// The MenuItemImage item.
            /// </summary>
            [RepositoryItem("c534f3e8-ec0d-46c8-a2c6-2c602c153371")]
            public virtual Ranorex.ATag MenuItemImage
            {
                get
                {
                    return _menuitemimageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MenuItemImage item info.
            /// </summary>
            [RepositoryItemInfo("c534f3e8-ec0d-46c8-a2c6-2c602c153371")]
            public virtual RepoItemInfo MenuItemImageInfo
            {
                get
                {
                    return _menuitemimageInfo;
                }
            }

            /// <summary>
            /// The txtProdName item.
            /// </summary>
            [RepositoryItem("f3331ba9-7219-4b94-8bfc-6c789f1991c6")]
            public virtual Ranorex.InputTag txtProdName
            {
                get
                {
                    return _txtprodnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtProdName item info.
            /// </summary>
            [RepositoryItemInfo("f3331ba9-7219-4b94-8bfc-6c789f1991c6")]
            public virtual RepoItemInfo txtProdNameInfo
            {
                get
                {
                    return _txtprodnameInfo;
                }
            }

            /// <summary>
            /// The txtMetatagtitle item.
            /// </summary>
            [RepositoryItem("3f720bf1-22be-4f42-8722-06ecd934e143")]
            public virtual Ranorex.InputTag txtMetatagtitle
            {
                get
                {
                    return _txtmetatagtitleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtMetatagtitle item info.
            /// </summary>
            [RepositoryItemInfo("3f720bf1-22be-4f42-8722-06ecd934e143")]
            public virtual RepoItemInfo txtMetatagtitleInfo
            {
                get
                {
                    return _txtmetatagtitleInfo;
                }
            }

            /// <summary>
            /// The txtModel item.
            /// </summary>
            [RepositoryItem("0167ac50-cdbd-4e40-a8ae-284190ece8a8")]
            public virtual Ranorex.InputTag txtModel
            {
                get
                {
                    return _txtmodelInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtModel item info.
            /// </summary>
            [RepositoryItemInfo("0167ac50-cdbd-4e40-a8ae-284190ece8a8")]
            public virtual RepoItemInfo txtModelInfo
            {
                get
                {
                    return _txtmodelInfo;
                }
            }

            /// <summary>
            /// The CheckBoxAJOA item.
            /// </summary>
            [RepositoryItem("183206ea-b5ed-4809-b3d2-f40e43d8183a")]
            public virtual Ranorex.InputTag CheckBoxAJOA
            {
                get
                {
                    return _checkboxajoaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CheckBoxAJOA item info.
            /// </summary>
            [RepositoryItemInfo("183206ea-b5ed-4809-b3d2-f40e43d8183a")]
            public virtual RepoItemInfo CheckBoxAJOAInfo
            {
                get
                {
                    return _checkboxajoaInfo;
                }
            }

            /// <summary>
            /// The btnImage item.
            /// </summary>
            [RepositoryItem("2880720d-213b-4ee8-8fd2-b72d05237533")]
            public virtual Ranorex.ATag btnImage
            {
                get
                {
                    return _btnimageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnImage item info.
            /// </summary>
            [RepositoryItemInfo("2880720d-213b-4ee8-8fd2-b72d05237533")]
            public virtual RepoItemInfo btnImageInfo
            {
                get
                {
                    return _btnimageInfo;
                }
            }

            /// <summary>
            /// The btnEditImage item.
            /// </summary>
            [RepositoryItem("596bc8be-0bef-4597-abec-a25e6efea4fb")]
            public virtual Ranorex.Button btnEditImage
            {
                get
                {
                    return _btneditimageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnEditImage item info.
            /// </summary>
            [RepositoryItemInfo("596bc8be-0bef-4597-abec-a25e6efea4fb")]
            public virtual RepoItemInfo btnEditImageInfo
            {
                get
                {
                    return _btneditimageInfo;
                }
            }

            /// <summary>
            /// The ImageFolder item.
            /// </summary>
            [RepositoryItem("21706f63-8ee2-4f6e-a14d-20e44c9cb734")]
            public virtual Ranorex.ITag ImageFolder
            {
                get
                {
                    return _imagefolderInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The ImageFolder item info.
            /// </summary>
            [RepositoryItemInfo("21706f63-8ee2-4f6e-a14d-20e44c9cb734")]
            public virtual RepoItemInfo ImageFolderInfo
            {
                get
                {
                    return _imagefolderInfo;
                }
            }

            /// <summary>
            /// The txtDateAvailable item.
            /// </summary>
            [RepositoryItem("9a1de261-fd81-4a25-9294-74110587558f")]
            public virtual Ranorex.InputTag txtDateAvailable
            {
                get
                {
                    return _txtdateavailableInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtDateAvailable item info.
            /// </summary>
            [RepositoryItemInfo("9a1de261-fd81-4a25-9294-74110587558f")]
            public virtual RepoItemInfo txtDateAvailableInfo
            {
                get
                {
                    return _txtdateavailableInfo;
                }
            }

            /// <summary>
            /// The txtEndDate item.
            /// </summary>
            [RepositoryItem("63d4a7d4-5b29-45c2-82dc-5acc6a7464d3")]
            public virtual Ranorex.InputTag txtEndDate
            {
                get
                {
                    return _txtenddateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtEndDate item info.
            /// </summary>
            [RepositoryItemInfo("63d4a7d4-5b29-45c2-82dc-5acc6a7464d3")]
            public virtual RepoItemInfo txtEndDateInfo
            {
                get
                {
                    return _txtenddateInfo;
                }
            }

            /// <summary>
            /// The EndDate item.
            /// </summary>
            [RepositoryItem("e6eaec65-3ed8-4627-a7c6-709e7bf8c4d6")]
            public virtual Ranorex.InputTag EndDate
            {
                get
                {
                    return _enddateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EndDate item info.
            /// </summary>
            [RepositoryItemInfo("e6eaec65-3ed8-4627-a7c6-709e7bf8c4d6")]
            public virtual RepoItemInfo EndDateInfo
            {
                get
                {
                    return _enddateInfo;
                }
            }

            /// <summary>
            /// The btnSave item.
            /// </summary>
            [RepositoryItem("3b596eec-9f9e-4e4b-8675-80d11414cf2c")]
            public virtual Ranorex.Button btnSave
            {
                get
                {
                    return _btnsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSave item info.
            /// </summary>
            [RepositoryItemInfo("3b596eec-9f9e-4e4b-8675-80d11414cf2c")]
            public virtual RepoItemInfo btnSaveInfo
            {
                get
                {
                    return _btnsaveInfo;
                }
            }

            /// <summary>
            /// The MenuCheckbox item.
            /// </summary>
            [RepositoryItem("f22c1afc-be1e-4bdd-8287-2ffae478de51")]
            public virtual Ranorex.DivTag MenuCheckbox
            {
                get
                {
                    return _menucheckboxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MenuCheckbox item info.
            /// </summary>
            [RepositoryItemInfo("f22c1afc-be1e-4bdd-8287-2ffae478de51")]
            public virtual RepoItemInfo MenuCheckboxInfo
            {
                get
                {
                    return _menucheckboxInfo;
                }
            }

            /// <summary>
            /// The txtPrice item.
            /// </summary>
            [RepositoryItem("f262e6e4-5078-46cd-9560-f43c76c2cce8")]
            public virtual Ranorex.InputTag txtPrice
            {
                get
                {
                    return _txtpriceInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPrice item info.
            /// </summary>
            [RepositoryItemInfo("f262e6e4-5078-46cd-9560-f43c76c2cce8")]
            public virtual RepoItemInfo txtPriceInfo
            {
                get
                {
                    return _txtpriceInfo;
                }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("bf7565d0-3668-4383-ad4c-657dfd2d93e8")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnlogoutInfo;
            RepoItemInfo _listmenuInfo;
            RepoItemInfo _menuisopenInfo;
            RepoItemInfo _parentmenuInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "bf7565d0-3668-4383-ad4c-657dfd2d93e8", "")
            {
                _btnlogoutInfo = new RepoItemInfo(this, "btnLogout", ".//header[#'header']//span[@class='hidden-xs hidden-sm hidden-md']", ".//header[#'header']/?/?/ul/li[2]/a[@href>'https://ptn-test1.oc.mbas']", 30000, null, "9a6ea782-30d1-4564-80ca-4148da3bda63");
                _listmenuInfo = new RepoItemInfo(this, "ListMenu", ".//nav[#'column-left']//ul[#'menu']", ".//nav[#'column-left']", 30000, null, "36368176-a0b3-46d5-84cc-aa4fc31ec85f");
                _menuisopenInfo = new RepoItemInfo(this, "MenuIsOpen", ".//nav[#'column-left']//ul[#'menu']//li[#$parentMenu]//a[@aria-expanded='true']", "", 30000, null, "a748bbd2-573d-4a50-b6d3-5cb7e759c2d7");
                _parentmenuInfo = new RepoItemInfo(this, "parentMenu", ".//a[@innertext<$parentname]", "", 30000, null, "70fc3682-a0ff-4d3a-b05f-56c2c108609a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bf7565d0-3668-4383-ad4c-657dfd2d93e8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnLogout item.
            /// </summary>
            [RepositoryItem("9a6ea782-30d1-4564-80ca-4148da3bda63")]
            public virtual Ranorex.SpanTag btnLogout
            {
                get
                {
                    return _btnlogoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The btnLogout item info.
            /// </summary>
            [RepositoryItemInfo("9a6ea782-30d1-4564-80ca-4148da3bda63")]
            public virtual RepoItemInfo btnLogoutInfo
            {
                get
                {
                    return _btnlogoutInfo;
                }
            }

            /// <summary>
            /// The ListMenu item.
            /// </summary>
            [RepositoryItem("36368176-a0b3-46d5-84cc-aa4fc31ec85f")]
            public virtual Ranorex.UlTag ListMenu
            {
                get
                {
                    return _listmenuInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The ListMenu item info.
            /// </summary>
            [RepositoryItemInfo("36368176-a0b3-46d5-84cc-aa4fc31ec85f")]
            public virtual RepoItemInfo ListMenuInfo
            {
                get
                {
                    return _listmenuInfo;
                }
            }

            /// <summary>
            /// The MenuIsOpen item.
            /// </summary>
            [RepositoryItem("a748bbd2-573d-4a50-b6d3-5cb7e759c2d7")]
            public virtual Ranorex.ATag MenuIsOpen
            {
                get
                {
                    return _menuisopenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MenuIsOpen item info.
            /// </summary>
            [RepositoryItemInfo("a748bbd2-573d-4a50-b6d3-5cb7e759c2d7")]
            public virtual RepoItemInfo MenuIsOpenInfo
            {
                get
                {
                    return _menuisopenInfo;
                }
            }

            /// <summary>
            /// The parentMenu item.
            /// </summary>
            [RepositoryItem("70fc3682-a0ff-4d3a-b05f-56c2c108609a")]
            public virtual Ranorex.ATag parentMenu
            {
                get
                {
                    return _parentmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The parentMenu item info.
            /// </summary>
            [RepositoryItemInfo("70fc3682-a0ff-4d3a-b05f-56c2c108609a")]
            public virtual RepoItemInfo parentMenuInfo
            {
                get
                {
                    return _parentmenuInfo;
                }
            }
        }

        /// <summary>
        /// The AJOA_PageAppFolder folder.
        /// </summary>
        [RepositoryFolder("355531b7-a670-44f7-9e86-516d6632bdc3")]
        public partial class AJOA_PageAppFolder : RepoGenBaseFolder
        {
            MBA_TestingRepositoryFolders.LoginPageFolder _loginpage;
            MBA_TestingRepositoryFolders.HomePageFolder1 _homepage;
            MBA_TestingRepositoryFolders.AddToCartFolder _addtocart;

            /// <summary>
            /// Creates a new AJOA_Page  folder.
            /// </summary>
            public AJOA_PageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AJOA_Page", "/dom[@domain='ajoa.ptn-test1.oc.mbasrv.com']", parentFolder, 30000, null, false, "355531b7-a670-44f7-9e86-516d6632bdc3", "")
            {
                _loginpage = new MBA_TestingRepositoryFolders.LoginPageFolder(this);
                _homepage = new MBA_TestingRepositoryFolders.HomePageFolder1(this);
                _addtocart = new MBA_TestingRepositoryFolders.AddToCartFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("355531b7-a670-44f7-9e86-516d6632bdc3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("355531b7-a670-44f7-9e86-516d6632bdc3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPage folder.
            /// </summary>
            [RepositoryFolder("69279db7-be28-46fc-81c5-e1dc7e5a36f8")]
            public virtual MBA_TestingRepositoryFolders.LoginPageFolder LoginPage
            {
                get { return _loginpage; }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("4a0fa2b3-8f35-4904-a77b-a56ba8602d44")]
            public virtual MBA_TestingRepositoryFolders.HomePageFolder1 HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The AddToCart folder.
            /// </summary>
            [RepositoryFolder("9ee42962-088f-4803-b496-8c18f8d177e2")]
            public virtual MBA_TestingRepositoryFolders.AddToCartFolder AddToCart
            {
                get { return _addtocart; }
            }
        }

        /// <summary>
        /// The LoginPageFolder folder.
        /// </summary>
        [RepositoryFolder("69279db7-be28-46fc-81c5-e1dc7e5a36f8")]
        public partial class LoginPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnlogoutInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _txtemailInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnlginInfo;

            /// <summary>
            /// Creates a new LoginPage  folder.
            /// </summary>
            public LoginPageFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPage", "", parentFolder, 0, null, false, "69279db7-be28-46fc-81c5-e1dc7e5a36f8", "")
            {
                _btnlogoutInfo = new RepoItemInfo(this, "btnLogout", "body//a[@href>'https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=account/logout']", ".//header/div[1]/div[2]/div[3]/div[1]/div/ul/li[2]/a[@href>'https://ajoa.ptn-test1.oc']", 30000, null, "4f208a57-c279-4468-b1c3-2e0162c45d60");
                _btnloginInfo = new RepoItemInfo(this, "btnLogin", "body//a[@href>'javascript:open_login_pop']", ".//a[@href>'javascript:open_login_pop']", 30000, null, "f05c1052-0936-461c-8687-1415f8493c8b");
                _txtemailInfo = new RepoItemInfo(this, "txtEmail", "body//iframe[@src='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=account/login&popup=login']//input[#'input-email']", ".//iframe[@src='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=account/login&popup=login']//input[#'input-email']", 30000, null, "87c9ec58-28f8-429c-b225-7f7d17aa808d");
                _txtpasswordInfo = new RepoItemInfo(this, "txtPassword", "body//iframe[@src='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=account/login&popup=login']//input[#'input-password']", ".//iframe[@src='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=account/login&popup=login']//input[#'input-password']", 30000, null, "a29ed548-c9d7-4104-9403-c5b8bb98fdbe");
                _btnlginInfo = new RepoItemInfo(this, "btnLgin", "body//form//button[@type='submit']", ".//iframe[@src='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=account/login&popup=login']//button", 30000, null, "6ddb101c-8d46-4347-8602-f06282f4bbc1");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("69279db7-be28-46fc-81c5-e1dc7e5a36f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnLogout item.
            /// </summary>
            [RepositoryItem("4f208a57-c279-4468-b1c3-2e0162c45d60")]
            public virtual Ranorex.ATag btnLogout
            {
                get
                {
                    return _btnlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnLogout item info.
            /// </summary>
            [RepositoryItemInfo("4f208a57-c279-4468-b1c3-2e0162c45d60")]
            public virtual RepoItemInfo btnLogoutInfo
            {
                get
                {
                    return _btnlogoutInfo;
                }
            }

            /// <summary>
            /// The btnLogin item.
            /// </summary>
            [RepositoryItem("f05c1052-0936-461c-8687-1415f8493c8b")]
            public virtual Ranorex.ATag btnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnLogin item info.
            /// </summary>
            [RepositoryItemInfo("f05c1052-0936-461c-8687-1415f8493c8b")]
            public virtual RepoItemInfo btnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The txtEmail item.
            /// </summary>
            [RepositoryItem("87c9ec58-28f8-429c-b225-7f7d17aa808d")]
            public virtual Ranorex.InputTag txtEmail
            {
                get
                {
                    return _txtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtEmail item info.
            /// </summary>
            [RepositoryItemInfo("87c9ec58-28f8-429c-b225-7f7d17aa808d")]
            public virtual RepoItemInfo txtEmailInfo
            {
                get
                {
                    return _txtemailInfo;
                }
            }

            /// <summary>
            /// The txtPassword item.
            /// </summary>
            [RepositoryItem("a29ed548-c9d7-4104-9403-c5b8bb98fdbe")]
            public virtual Ranorex.InputTag txtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPassword item info.
            /// </summary>
            [RepositoryItemInfo("a29ed548-c9d7-4104-9403-c5b8bb98fdbe")]
            public virtual RepoItemInfo txtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The btnLgin item.
            /// </summary>
            [RepositoryItem("6ddb101c-8d46-4347-8602-f06282f4bbc1")]
            public virtual Ranorex.Button btnLgin
            {
                get
                {
                    return _btnlginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLgin item info.
            /// </summary>
            [RepositoryItemInfo("6ddb101c-8d46-4347-8602-f06282f4bbc1")]
            public virtual RepoItemInfo btnLginInfo
            {
                get
                {
                    return _btnlginInfo;
                }
            }
        }

        /// <summary>
        /// The HomePageFolder1 folder.
        /// </summary>
        [RepositoryFolder("4a0fa2b3-8f35-4904-a77b-a56ba8602d44")]
        public partial class HomePageFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _txtsearchInfo;
            RepoItemInfo _btnsearchInfo;
            RepoItemInfo _btnlogoutInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder1(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "4a0fa2b3-8f35-4904-a77b-a56ba8602d44", "")
            {
                _txtsearchInfo = new RepoItemInfo(this, "txtSearch", ".//div[#'search']//span/input[@name='search']", ".//div[#'search']//input[@name='search']", 30000, null, "ec249b60-687e-488b-897e-53ed109f7e04");
                _btnsearchInfo = new RepoItemInfo(this, "btnSearch", ".//div[#'search']//button[@class='search-button']", ".//div[#'search']/div/div/button", 30000, null, "0ef9be10-ee99-4afc-89b2-0ba7f3efc01e");
                _btnlogoutInfo = new RepoItemInfo(this, "btnLogout", ".//header//div[@class='top-menu top-menu-240']//li[@class='menu-item top-menu-item top-menu-item-8']", ".//header/div[1]/div[2]/div[3]/div[1]/div/ul/li[2]/a[@href>'https://ajoa.ptn-test1.oc']", 30000, null, "15cd94f7-8e9f-4c4b-9999-e5d481a3d837");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a0fa2b3-8f35-4904-a77b-a56ba8602d44")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtSearch item.
            /// </summary>
            [RepositoryItem("ec249b60-687e-488b-897e-53ed109f7e04")]
            public virtual Ranorex.InputTag txtSearch
            {
                get
                {
                    return _txtsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtSearch item info.
            /// </summary>
            [RepositoryItemInfo("ec249b60-687e-488b-897e-53ed109f7e04")]
            public virtual RepoItemInfo txtSearchInfo
            {
                get
                {
                    return _txtsearchInfo;
                }
            }

            /// <summary>
            /// The btnSearch item.
            /// </summary>
            [RepositoryItem("0ef9be10-ee99-4afc-89b2-0ba7f3efc01e")]
            public virtual Ranorex.Button btnSearch
            {
                get
                {
                    return _btnsearchInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSearch item info.
            /// </summary>
            [RepositoryItemInfo("0ef9be10-ee99-4afc-89b2-0ba7f3efc01e")]
            public virtual RepoItemInfo btnSearchInfo
            {
                get
                {
                    return _btnsearchInfo;
                }
            }

            /// <summary>
            /// The btnLogout item.
            /// </summary>
            [RepositoryItem("15cd94f7-8e9f-4c4b-9999-e5d481a3d837")]
            public virtual Ranorex.LiTag btnLogout
            {
                get
                {
                    return _btnlogoutInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The btnLogout item info.
            /// </summary>
            [RepositoryItemInfo("15cd94f7-8e9f-4c4b-9999-e5d481a3d837")]
            public virtual RepoItemInfo btnLogoutInfo
            {
                get
                {
                    return _btnlogoutInfo;
                }
            }
        }

        /// <summary>
        /// The AddToCartFolder folder.
        /// </summary>
        [RepositoryFolder("9ee42962-088f-4803-b496-8c18f8d177e2")]
        public partial class AddToCartFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaddtocartInfo;
            RepoItemInfo _btncartInfo;
            RepoItemInfo _listproductInfo;
            RepoItemInfo _listfoundproductInfo;
            RepoItemInfo _listproductcartInfo;

            /// <summary>
            /// Creates a new AddToCart  folder.
            /// </summary>
            public AddToCartFolder(RepoGenBaseFolder parentFolder) :
                    base("AddToCart", "", parentFolder, 0, null, false, "9ee42962-088f-4803-b496-8c18f8d177e2", "")
            {
                _btnaddtocartInfo = new RepoItemInfo(this, "btnAddToCart", ".//a[#'button-cart']", ".//a[#'button-cart']", 30000, null, "0cbd5154-72ae-4b65-9783-5c320526436a");
                _btncartInfo = new RepoItemInfo(this, "btnCart", "body//div[@id='cart']//i[@class='fa fa-shopping-cart']", ".//header/div[1]/div[2]/div[3]/div[3]/div[@id='cart']/a[@href>'https://ajoa.ptn-test1.oc']/i", 30000, null, "c43845ab-2305-4706-a994-2e2407745b6e");
                _listproductInfo = new RepoItemInfo(this, "ListProduct", ".//div[#'content']//form[@action='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=checkout/cart/edit']//table//tbody", "", 30000, null, "e91eab05-0fd3-4776-ab2d-fc0140390d88");
                _listfoundproductInfo = new RepoItemInfo(this, "ListFoundProduct", ".//div[#'content']//div[@class='main-products product-grid']", ".//div[#'content']/div[3]/div[2]", 30000, null, "b1924af1-c651-4de6-b3ad-b1529297d294");
                _listproductcartInfo = new RepoItemInfo(this, "ListProductCart", ".//div[#'content']//form[@action='https://ajoa.ptn-test1.oc.mbasrv.com/index.php?route=checkout/cart/edit']//table//tbody//a[@innertext<$parentList]", "element", 30000, null, "bfdd8781-e14a-47fa-a7fb-fc36f3dff548");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9ee42962-088f-4803-b496-8c18f8d177e2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAddToCart item.
            /// </summary>
            [RepositoryItem("0cbd5154-72ae-4b65-9783-5c320526436a")]
            public virtual Ranorex.ATag btnAddToCart
            {
                get
                {
                    return _btnaddtocartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The btnAddToCart item info.
            /// </summary>
            [RepositoryItemInfo("0cbd5154-72ae-4b65-9783-5c320526436a")]
            public virtual RepoItemInfo btnAddToCartInfo
            {
                get
                {
                    return _btnaddtocartInfo;
                }
            }

            /// <summary>
            /// The btnCart item.
            /// </summary>
            [RepositoryItem("c43845ab-2305-4706-a994-2e2407745b6e")]
            public virtual Ranorex.ITag btnCart
            {
                get
                {
                    return _btncartInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The btnCart item info.
            /// </summary>
            [RepositoryItemInfo("c43845ab-2305-4706-a994-2e2407745b6e")]
            public virtual RepoItemInfo btnCartInfo
            {
                get
                {
                    return _btncartInfo;
                }
            }

            /// <summary>
            /// The ListProduct item.
            /// </summary>
            [RepositoryItem("e91eab05-0fd3-4776-ab2d-fc0140390d88")]
            public virtual Ranorex.TBodyTag ListProduct
            {
                get
                {
                    return _listproductInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The ListProduct item info.
            /// </summary>
            [RepositoryItemInfo("e91eab05-0fd3-4776-ab2d-fc0140390d88")]
            public virtual RepoItemInfo ListProductInfo
            {
                get
                {
                    return _listproductInfo;
                }
            }

            /// <summary>
            /// The ListFoundProduct item.
            /// </summary>
            [RepositoryItem("b1924af1-c651-4de6-b3ad-b1529297d294")]
            public virtual Ranorex.DivTag ListFoundProduct
            {
                get
                {
                    return _listfoundproductInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ListFoundProduct item info.
            /// </summary>
            [RepositoryItemInfo("b1924af1-c651-4de6-b3ad-b1529297d294")]
            public virtual RepoItemInfo ListFoundProductInfo
            {
                get
                {
                    return _listfoundproductInfo;
                }
            }

            /// <summary>
            /// The ListProductCart item.
            /// </summary>
            [RepositoryItem("bfdd8781-e14a-47fa-a7fb-fc36f3dff548")]
            public virtual Ranorex.ATag ListProductCart
            {
                get
                {
                    return _listproductcartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ListProductCart item info.
            /// </summary>
            [RepositoryItemInfo("bfdd8781-e14a-47fa-a7fb-fc36f3dff548")]
            public virtual RepoItemInfo ListProductCartInfo
            {
                get
                {
                    return _listproductcartInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
